### ISSUE TITLE
Spinny ball "working" icon

### ISSUE THREAD

**Issue by field2** [ryelle/WordPress#28]
When you're doing stuff the spinning ball animated gif appears. We should do this with animated svg.

**Comment by grayghostvisuals** [comment]
@field2 Can you link me a screenshot of the gif and possibly the location on where I can find this? I'd like to tackle this if I could.

**Comment by field2** [comment]
spinner.gif is in src/wp-admin/images/spinner.gif and spinner-2x.gif
![spinner](https://cloud.githubusercontent.com/assets/1656980/20432674/4e16164a-ad6e-11e6-856e-4ab6f4085d29.gif)

**Comment by grayghostvisuals** [comment]
@field2 Here is my version using CSS. No SVG or gif needed.

[http://codepen.io/grayghostvisuals/pen/ogLemL?editors=0100](http://codepen.io/grayghostvisuals/pen/ogLemL?editors=0100)

![wp-loader](https://cloud.githubusercontent.com/assets/934322/20446991/64696ae6-adaa-11e6-8a82-fd4d03a07ead.gif)

**Comment by field2** [comment]
or http://codepen.io/empireoflight/pen/XNpzOw?editors=1100 ?

**Comment by grayghostvisuals** [comment]
@field2 What are your thoughts about my original demo?

**Comment by field2** [comment]
The main thing is the size is off-it should be 18x18. Other than that it's fine I think.

**Comment by grayghostvisuals** [comment]
ok 18 x 18 is all I need to know. standby

**Comment by grayghostvisuals** [comment]
@field2 I'm trying to find all the instances of this spinner and so far this is what I've found…

```php
wp-admin/customize.php
wp-admin/css/common.css
wp-admin/css/customize-controls.css
```

So far this is this list that makes sense but I've also found a few lines in `common.css` that are intriguing…

```css
body.about-php #TB_window.thickbox-loading:before,
body.plugin-install-php #TB_window.thickbox-loading:before,
body.import-php #TB_window.thickbox-loading:before,
body.plugins-php #TB_window.thickbox-loading:before,
body.update-core-php #TB_window.thickbox-loading:before,
body.index-php #TB_window.thickbox-loading:before {
	content: "";
	display: block;
	width: 20px;
	height: 20px;
	position: absolute;
	left: 50%;
	top: 50%;
	z-index: -1;
	margin: -10px 0 0 -10px;
	background: #fcfcfc url(../images/spinner.gif) no-repeat center;
	-webkit-background-size: 20px 20px;
	background-size: 20px 20px;
	-webkit-transform: translateZ(0);
	transform: translateZ(0);
}

@media print,
	(-webkit-min-device-pixel-ratio: 1.25),
	(min-resolution: 120dpi) {

	body.about-php #TB_window.thickbox-loading:before,
	body.plugin-install-php #TB_window.thickbox-loading:before,
	body.import-php #TB_window.thickbox-loading:before,
	body.plugins-php #TB_window.thickbox-loading:before,
	body.update-core-php #TB_window.thickbox-loading:before,
	body.index-php #TB_window.thickbox-loading:before {
		background-image: url(../images/spinner-2x.gif);
	}
}
```
